cmd/cmrel/cmd/gcb_publish.go
cmd/cmrel/cmd/gcb_stage.go
pkg/release/consts.go
pkg/release/unpacker.go

This adds support to the release tooling for the recently added UBI based docker images: https://github.com/jetstack/cert-manager/pull/2746
In order to have parity with Red Hat's own base image architectures, this also expands the number of architectures we release cert-manager for to include s390x and ppc64le.
/kind feature
/milestone v0.15

Add support for UBI images and additional architectures

---

pkg/release/validation/validate.go

See https://console.cloud.google.com/cloud-build/builds/aea169f4-5496-448d-b331-f8f4951fd402;step=2?project=cert-manager-release
The current release-0.15 branch is failing to release because the 'component name' is of the format `controller-ubi`, which is incorrect.
We need to improve the release tooling to better understand component names to work around this (or change how the artifacts are built in the cert-manager repo).
For now, this adds a check to the validator that will cause the release to fail earlier on if this happens.
/assign @meyskens

Validate built image name uses is correct/expected

---

pkg/release/unpacker.go
pkg/release/validation/validate.go

1) fix the validation added in #5 to actually check UBI images (and do it properly)
2) fix parsing of 'component name' for UBI images by manually trimming the `-ubi` suffix from the component name when unpacking UBI images. This depends on us _not_ changing the name of the Bazel target in `//build` in the main repo.
This should unblock the v0.15.0-alpha.0 release 😄 
/assign @meyskens

Fix image name validation & properly handle UBI image names

---

cmd/cmrel/cmd/gcb_publish.go

Avoids the following errors in the release publish step:
```
Step #2: 2020/04/08 14:55:18 Pushed UBI release image "quay.io/jetstack/cert-manager-controller-s390x:v0.15.0-alpha.0-ubi"
Step #2: 2020/04/08 14:55:20 Creating multi-arch manifest lists for UBI image components
Step #2: 2020/04/08 14:55:20 Creating manifest list "quay.io/jetstack/cert-manager-controller:v0.15.0-alpha.0"
Step #2: refusing to amend an existing manifest list with no --amend flag
Step #2: 2020/04/08 14:55:20 Failed to create manifest list with name "quay.io/jetstack/cert-manager-controller:v0.15.0-alpha.0" - ensure no existing manifest list exists with the same name, and ensure all member images are pushed to the remote registry.
Step #2: 2020/04/08 14:55:20 ERROR OCCURRED DURING PUBLISHING - INCOMPLETE RELEASE MAY …
```

Fix release version used for UBI manifest lists

---

cmd/cmrel/cmd/gcb_publish.go
pkg/release/binaries/tar.go
pkg/release/unpacker.go

Makes changes to the new binary name and to release it as a .tar.gz
I still refer to it in the function names as `ctl` not to make the names too long, alternative names welcome!

Release CLI binaries as a .tar.gz

---

cmd/cmrel/cmd/gcb_stage.go
test/presubmit.sh

Adds a basic presubmit test. Requires https://github.com/jetstack/testing/pull/381 to merge so I can actually configure this.

Add test/presubmit.sh script

---

cmd/cmrel/cmd/gcb_publish.go
pkg/release/unpacker.go
pkg/release/validation/validate.go

Simplifies some of the logic and fixes up use of `filepath.Ext` 😅 
/assign @meyskens

Fix publishing kubectl-cert_manager binary artifacts

---

gcb/stage/cloudbuild.yaml

Required for the v0.16 release due to gazelle being bumped 😄

Upgrade bazel to 3.3.1

---

gcb/stage/cloudbuild.yaml

To match the version used in CI since https://github.com/jetstack/testing/pull/455

bump Bazel version  to v3.7.2

---

gcb/stage/cloudbuild.yaml

Latest version available in l.gcr.io/google/bazel is a little old.

Downgrades version of Bazel

---

pkg/release/consts.go

Builds `kubectl` plugin for `darwin/arm64`.
Fixes #25 

Add darwin/arm64 to list of os/arch for client binaries

---

README.md
cmd/cmrel/cmd/stage.go
pkg/release/consts.go

This PR updates the release tool to also build the cert-manager kubectl plugin for darwin/arm64.
Since, we already have darwin/arm64 in the list of supported os/arch combinations for the kubectl plugin in cert-manager codebase [here](https://github.com/jetstack/cert-manager/blob/master/build/platforms.bzl#L40) this was just a matter of ensuring that we build the release artifacts with `--platforms=@io_bazel_rules_go//go/toolchain:darwin_arm64` flag from `cmrel`.
I have also updated the README and `cmrel stage --help` output a little.
I've created a 'development' build with the updated `cmrel` tool here https://console.cloud.google.com/storage/browser/cert-manager-release/stage/gcb/devel/5875c828c68b9e22ec157508743e360017916190?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D% …

Kubectl plugin for darwin arm64

---

gcb/publish/cloudbuild.yaml

Separated from #38  because I'm not 100% sure that this will be without any side effects.
There are even newer versions of docker available, but 19.03 was the latest updated in `gcr.io/cloud-builders/docker`.

Bump docker version used in codebuild

---

cmd/cmrel/cmd/staged.go
go.mod

Running `staged` was quite confusing since the versions would show in some random order. It now sorts versions lexicographically which means that the bottom lines are the latest tags.
Before:
```sh
% cmrel staged
NAME                                                           VERSION               DATE
v0.14.0-alpha.0-b057a72b467914a569329f45e0dc02bcfd9a8099       v0.14.0-alpha.0       UNKNOWN
v0.14.0-fullrelease.1-f6da9c76877551ef32503b17189bb178501f59a7 v0.14.0-fullrelease.1 UNKNOWN
v0.15.0-1d6ecc9cf8d841782acb5f3d3c28467c24c5fd18               v0.15.0               UNKNOWN
v1.1.0-alpha.1-fda1c091e3f37046c378bbf832e603284b6db531        v1.1.0-alpha.1        UNKNOWN
v1.2.0-alpha.1-33f18811909bdd08d39fd8aa3f016734d1393d18        v1.2.0-alpha.1        UNKNOWN …
```

Sort versions when running "cmrel staged" and add cmrel staged --help

---

hack/helm_keyring.sh

These keyrings are required by helm for validating signed charts; this script is intended to remove the need to remember gpg commands manually :grin:

Add script for generating a GPG keyring from an armored key

---

cmd/cmrel/cmd/gcb_stage.go
pkg/release/consts.go
pkg/release/platforms.go

This is mostly to clean up [this line](https://github.com/cert-manager/release/blob/4d52f6f9027b2330897cc2014e1af8628bc63d22/cmd/cmrel/cmd/gcb_stage.go#L165) which I found very hard to parse (and which has an extra append left over from previous changes).
This will also make it easier to add flags to specify a specific OS or arch to build later, by manually specifying a value for osTargets

Minor cleanup of gcb stage command

---

README.md
cmd/cmrel/cmd/stage.go
gcb/publish/cloudbuild.yaml
gcb/stage/cloudbuild.yaml
pkg/release/consts.go
test/presubmit.sh

Following the move from github.com/jetstack/cert-manager to github.com/cert-manager/cert-manager
* https://github.com/cert-manager/cert-manager/issues/4824

Update cmrel to use the new cert-manager organization on GitHub

---

cmd/cmrel/cmd/gcb_publish.go
gcb/publish/cloudbuild.yaml

Now that quay supports signing, we can enable container signing again!

Re-enable container signing and bump cosign version

---

cmd/cmrel/cmd/makestage.go
gcb/makestage/cloudbuild.yaml
pkg/release/github.go

Also does some cleanup of makestage, simplifies things, and adds output of the GCS target path in console
Part of the migration to make: https://github.com/cert-manager/cert-manager/issues/4712

Save makestage artifacts at the same location stage artifacts are saved

---

cmd/cmrel/cmd/makestage.go
gcb/makestage/cloudbuild.yaml

Can be merged now that following prerequisite PRs have both merged:
- https://github.com/cert-manager/cert-manager/pull/5209
- https://github.com/cert-manager/cert-manager/pull/5205
This PR has a few commits, each of which is self-contained and individually reviewable.
The first removes our manual installation of `jq` since we added that to the `bazelbuild` image in https://github.com/jetstack/testing/pull/68.
The second removes a comment which wasn't really relevant to this file (I think it was copy-pasted).
The third uses the `make publish-release` target that was added to the cert-manager repo instead of the manual `gsutil` commands we used to release 1.8 originally.

Use `make publish-release` / update builder image

---

cmd/cmrel/cmd/makestage.go

The path to which we write staged releases is now simpler for tagged
releases, and the release process has been simplified to reflect this.
We no longer need to calculate this path, nor do we need to output it.
A maintainer performing a release can simply use their `RELEASE_VERSION`
variable which they already have.

Reduce work + simplify output

---

gcb/bootstrap-pgp/cloudbuild.yaml
gcb/publish/cloudbuild.yaml
gcb/stage/cloudbuild.yaml
gcb/test/helm/cloudbuild.yaml
go.mod
test/presubmit.sh

Spotted as part of release of cert-manager 1.9

Bump gcb versions of go to 1.18

---

prowspecs/specs.go

Note: we don't support 1.19 for 1.9, but I didn't really think about that when I wrote the generation stuff.
We could have 4 release channels to address that - "old", "previous", "current" and "next". Or we could allow a subset of k8s versions to be used for some branches. But we don't need to shave that yak now, I don't think!

Changes required post release of 1.9

---

cmd/cmrel/cmd/generate_prow.go
pkg/prowgen/context.go
prowspecs/specs.go

This includes generating presubmit/periodic dashboard names, incorporatingbranch names into test names and removing the concept of 'modes'

Generate tests based on a single branch name

---

pkg/prowgen/generators.go

Tests are [currently failing](https://testgrid.k8s.io/cert-manager-periodics-master#ci-cert-manager-master-trivy-test-controller) because of a lack of docker.

Enable dind for trivy jobs

---

pkg/prowgen/context.go
pkg/prowgen/generators.go
prowspecs/specs.go

Hard code and pin images for previous release branches
This makes the output of `cmrel` match `jetstack/testing` for _all_ branches.

Adds Image to prow context, pass context to job generators.

---

.github/workflows/update-prow-config.yaml
.github/workflows/verify.yaml
cmd/cmrel/cmd/generate_prow.go
prowspecs/specs.go

This PR adds a new flag `--output` to `generate-prow`. The default `stdout` value prints to stdout as it does currently. `file` will write the prow config to a directory and file in form `<branch>/cert-manager-<branch>.yaml` to mimic the [existing path structure](https://github.com/jetstack/testing/tree/master/config/jobs/cert-manager/cert-manager).
The `branches` flag now also accepts a value of `*` which will loop over all existing known branches.
---
A github workflow is added which (hopefully) runs the generate command when a `cert-manager/release` PR is merged. If the output is different to what is currently in `jetstack/testing`, then a PR will be opened with the changes.
This new workflow uses `peter-evans/create-pull-request@v4`. I don't know how we using a third party action like …

Option to write generated prow config, and automatically create pull request against jetstack/testing

---

pkg/prowgen/globals.go

Signed-off-by: joshvanl <me@joshvanl.dev>
/assign @inteon 
See: https://console.cloud.google.com/gcr/images/jetstack-build-infra-images/EU/bazelbuild?tag=20220629-ee75d11

Update CommonImageTest to 20220812-2f64076-4.2.1

---

prowspecs/specs.go

Added 1.25 as the default Kubernetes test version for all tests.

Add 1.25 as default testing Kubernetes version

---

.github/workflows/generate-prow-tests-specs.yaml

We want the action to run on master, so that we have an up-to-date patch for the testing repo.

Run gh action on master

---

pkg/prowgen/generators.go

@maelvls and I noticed that the tests were added to the wrong test in @jahrlin's PR (https://github.com/jetstack/testing/pull/748). I based https://github.com/cert-manager/release/pull/98 on this PR, so this is wrong.
This PR contains the fix and moves the tests to E2E.

Fix: move lifecycle from Test to E2ETest

---

prowspecs/specs.go

cert-manager versions 1.8 and 1.9 are not targeted for support for Kubernetes `v1.25`. Given that we are going to release a new cert-manager version soon with support for `v1.25`, I don't think it makes sense to be running periodic tests for it- especially when we will need to at least backport a kind version bump PR.

Removes 1.25 as a Kubernetes target for cert-manager versions 1.8 and 1.9

---

prowspecs/specs.go

This PR makes K8s v1.25 the default version for presubmits on master
Signed-off-by: Joakim Ahrlin <joakim.ahrlin@gmail.com>

make k8s 1.25 default

---

pkg/prowgen/context.go
pkg/prowgen/generators.go
pkg/prowgen/types.go
prowspecs/specs.go

Also adds standalone licenses test; after this merges we can remove the licenses test from [`ci-presubmit`](https://github.com/cert-manager/cert-manager/blob/37ae8b2773c44e48df85d974ea9ea79dbacadea2/make/ci.mk#L6).

Add ability to trigger presubmits when named files change

---

prowspecs/specs.go

Now that https://github.com/cert-manager/cert-manager/pull/5646 is merged, we can default to testing using k8s 1.26 on master
After this merges, we can merge https://github.com/jetstack/testing/pull/779 which applies these changes.

Default to testing 1.26 on master

---

pkg/prowgen/configurers.go
pkg/prowgen/context.go
pkg/prowgen/generators.go

Ensures that if trivy tests haven't run for 36 hours we'll be alerted (we currently run every 24h).
Also ensures that any failure is treated as an actual failure which stops the test getting marked as 'flaky'

Change alerting for trivy tests

---

pkg/prowgen/configurers.go
pkg/prowgen/generators.go
prowspecs/specs.go

And optionally on pull requests.
Applied in:
* https://github.com/jetstack/testing/pull/787
Follows up:
* https://github.com/cert-manager/cert-manager/pull/5754
* https://github.com/cert-manager/cert-manager/issues/5254

Run the best-practice installation tests daily

---

prowspecs/specs.go

As cert-manager 1.12 will not support k8s 1.21
See https://cert-manager.io/docs/installation/supported-releases/

Removes k8s 1.21 tests for master

---

pkg/prowgen/globals.go

This image was created by https://github.com/jetstack/testing/pull/799

Use newer bazelbuild image for cert-manager master

---

Makefile
cmd/cmrel/cmd/root.go
cmd/cmrel/cmd/validate_gomod.go
hack/test-validate-gomod-success.sh
hack/test-validate-gomod.sh
validate-gomod-test/broken/cmd/acmesolver/go.mod
validate-gomod-test/broken/cmd/cainjector/go.mod
validate-gomod-test/broken/cmd/controller/go.mod
validate-gomod-test/broken/cmd/ctl/go.mod
validate-gomod-test/broken/cmd/webhook/go.mod
validate-gomod-test/broken/go.mod
validate-gomod-test/broken/test/e2e/go.mod
validate-gomod-test/broken/test/integration/go.mod
validate-gomod-test/valid/cmd/acmesolver/go.mod
validate-gomod-test/valid/cmd/cainjector/go.mod
validate-gomod-test/valid/cmd/controller/go.mod
validate-gomod-test/valid/cmd/ctl/go.mod
validate-gomod-test/valid/cmd/webhook/go.mod
validate-gomod-test/valid/go.mod
validate-gomod-test/valid/test/e2e/go.mod
validate-gomod-test/valid/test/integration/go.mod

This PR adds a new `validate-gomod` command to `cmrel`, which checks certain aspects of various go.mod files which are added by https://github.com/cert-manager/cert-manager/pull/5880 ([design doc](https://github.com/cert-manager/cert-manager/pull/5843)).
The functionality of this subcommand should be clear from its description (see `validateGoModLongDescription`).
Also provided are test environments; these tests will be run as part of CI for this PR.

go.mod Smoke Test Subcommand

---

pkg/prowgen/configurers.go
pkg/prowgen/generators.go
pkg/prowgen/globals.go
pkg/prowgen/types.go
prowspecs/specs.go

Based on changes we made in https://github.com/jetstack/testing
In https://github.com/jetstack/testing, we removed the -j limitations. This however has not yet proven to be a great improvement, so we shouldn't upstream that change here yet.
The value `Agent: "kubernetes",` was removed because this is the default prowjob value. An empty value is thus identical to not specifying this value.

Use make-dind, update requested resources and remove default values

---

gcb/bootstrap-pgp/cloudbuild.yaml
gcb/publish/cloudbuild.yaml
gcb/stage/cloudbuild.yaml
gcb/test/helm/cloudbuild.yaml

I'm trying to fix this issue: https://console.cloud.google.com/cloud-build/builds/2951bbf6-86cd-4c36-8d5c-f7a111c31c07?project=cert-manager-release

Bump gcb images from 1.18 to 1.21

---

cmd/cmrel/cmd/gcb_publish.go
cmd/cmrel/cmd/gcb_stage.go
pkg/release/platforms.go
pkg/release/platforms_test.go
pkg/release/unpacker.go
pkg/release/validation/validate.go

We removed cmctl from the `./cmd/ctl` in the main repository and moved it in the repository https://github.com/cert-manager/cmctl.
I propose to add some logic that will skip the binaries and containers for `./cmd/ctl`.
~I'm not sure how this will play out for the `startupapicheck` container used in the Helm chart since the Helm chart currently uses a single version for all containers. We need to figure this out before this PR is merged!~ All is well since the startupapicheck binary still belongs to the cert-manager project and will still be pushed.
**Manual testing while releasing 1.15.0-alpha.0**
First, I had to point to my branch (rg = ripgrep):
```bash
rg _RELEASE_REPO_REF --files-with-matches \
| xargs perl -pi -e 's/_RELEASE_REPO_REF:.*/_RELEASE_REPO_REF: …
```

Skip shipping cmctl for v1.15.0-alpha.0 and above

---

gcb/bootstrap-pgp/cloudbuild.yaml
gcb/publish/cloudbuild.yaml
gcb/stage/cloudbuild.yaml
gcb/test/helm/cloudbuild.yaml
pkg/release/unpacker.go

1. We need to use golang 1.22 images now that cmrel requires go1.22
2. There are no "cloud-builders" go 1.22 images so we need to switch to the docker `golang` images
3. That requires a few changes to the build steps to make it work
4. There's also a bug introduced in #168 which means that cmctl binaries aren't actually unpacked correctly
5. Also bumps the cosign version to the latest v1 (there's v2 available but I'm not fighting that battle yet)
[This cmrel publish dry-run](https://console.cloud.google.com/cloud-build/builds/3f4e48ef-b690-45a6-a682-9a5365b5eb0a?project=cert-manager-release) was run using this branch for this repo, which shows that the code fix works.

Various fixes for cmrel

---

gcb/makestage/cloudbuild.yaml

Fixes: https://github.com/cert-manager/cert-manager/issues/7307
* https://github.com/cert-manager/cert-manager/issues/7307
Assuming that the build failures are caused by OOM so testing whether reducing the parallelism might reduce the peak memory.
I ran `cmrel makestage` with this version of the cloudbuild.yaml file, and it succeeded.
> Total build time: 2 min 52 sec
- https://console.cloud.google.com/cloud-build/builds;region=global/8811ffbb-3ed0-46d1-8ffa-8c32fe5ab0a5;tab=detail?project=cert-manager-release
```console
$ cmrel makestage --ref=v1.16.0-beta.0
2024/09/26 10:52:01 Root options:
2024/09/26 10:52:01   Debug: false
2024/09/26 10:52:01 Stage options:
2024/09/26 10:52:01   Bucket: "cert-manager-release"
2024/09/26 10:52:01   Org: "cert-manager"
2024/09/26 10:52:01   Repo: …
```

Reduce parallelism and use supported machine type for makestage

---

cmd/cmrel/cmd/const.go
hack/push_and_sign_chart.sh

Comments in the script should hopefully explain its purpose and the caveats. Aim is for this to be run manually as part of the release process; I'll add this to the release process on the website once this is merged.
The `oci://quay.io/jetstack/charts/cert-manager:v1.15.1` chart is pushed using this script, as an example. Once this PR merges, I'll go through and manually re-push every tag newer than v1.8.0 (see the comments in the script for the reason why that specific version is my cutoff. I'd already manually pushed .prov-less versions of older charts, so I'll leave those in place)

Add script for manually pushing an OCI chart along with signatures
