cmd/cmrel/cmd/publish.go
cmd/cmrel/cmd/stage.go

Use the 'master' branch for the cmrel tool when launching GCB jobs

---

cmd/cmrel/cmd/gcb_publish.go
cmd/cmrel/cmd/gcb_stage.go
pkg/release/consts.go
pkg/release/unpacker.go
pkg/release/validation/validate.go

Remove references to UBI images

---

cmd/cmrel/cmd/gcb_publish.go
cmd/cmrel/cmd/gcb_stage.go

Fix 'kubectl-cert_manager' release artifact name

---

go.mod
go.sum
pkg/release/validation/validate.go
pkg/release/validation/validate_test.go

Validate release version is semver compliant

---

pkg/release/consts.go

Reverting as it seems to have not worked #25 (comment).
Apologies for the noise.
Reverts #26
/kind cleanup

Revert "Add darwin/arm64 to list of os/arch for client binaries"

---

cmd/cmrel/cmd/gcb_publish.go

Fixes: https://github.com/cert-manager/release/issues/33

Fix nil pointer error / supply a GitHub UsersClient

---

README.md
cmd/cmrel/cmd/gcb_stage.go
cmd/cmrel/cmd/staged.go
gcb/publish/cloudbuild.yaml
gcb/stage/cloudbuild.yaml
gcb/test/helm/cloudbuild.yaml
pkg/gcb/gcb.go
pkg/release/helm/helm.go
pkg/release/tar/tarball.go
pkg/release/unpacker.go

See individual commit messages for details; these changes should hopefully be uncontroversial.

Small cleanups of code

---

gcb/stage/cloudbuild.yaml

To be merged after testing in cert-manager experimental

bump bazel to 4.2.1

---

README.md
cmd/cmrel/cmd/publish.go
hack/verify_boilerplate.py

Raising as a separate PR to avoid complicating the main signing PRs when they come.

Py3 for boilerplate check, control flow docs + trivial tweak to code

---

gcb/stage/cloudbuild.yaml

Get the bazel image from gcr.io/cloud-builders 

---

pkg/sign/kmspgp.go

Reasoning is explained in a comment on `keyCreationTimeUnix` in `pkg/sign/kmspgp.go`
In short, this is required because we need static KMS key IDs and that's only possible with a static creation time unless we add more API calls.
Also slightly refactors the handling of `packet.Config`, which we don't really need to modify manually

Ensure that all keys use a static time

---

README.md

See https://github.com/cert-manager/csi-driver/pull/80 for justification on attributes

add logo to harmonize with other org projects

---

README.md

Will stealth merge because this is trivial

Update to smaller logo

---

pkg/prowgen/generators.go
prowspecs/specs.go

See the comment for TrivyTest for the justification as to why we don't just run `make trivy-scan-all`!
Backports were abandoned (#5365 and #5367) , so this only focuses on master.

Add generator for trivy scan tests

---

.github/workflows/update-prow-config.yaml

Signed-off-by: joshvanl <me@joshvanl.dev>

Run git config add safe directory before making changes to testing

---

pkg/prowgen/generators.go
pkg/prowgen/types.go

This change is already present on our testing infra ( was added for testing by @jahrlin ).

Add prestop hook

---

prowspecs/specs.go

Signed-off-by: Joakim Ahrlin <joakim.ahrlin@gmail.com>

remove ProwJobs for release-1.8

---

cmd/cmrel/cmd/generate_prow.go
pkg/prowgen/generators.go

See commit messages for more detailed information

Make trivy jobs privileged, improve CLI experience

---

OWNERS

I am already an approver on cm/cm, this subrepo is part of the release tooling for that main project, so makes sense for me to also have approver status here.

chore: add @thatsmrtalbot as approver

---

cmd/cmrel/cmd/gcb_publish.go

This looks like a bug which was introduced in #169

Upload cmctl binaries for releases which need them
